
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * Managed by better-auth core, with Cache-specific user preferences added.
 * Do not rename auth-owned fields; better-auth reads them by convention.
 */
export type User = Prisma.UserModel
/**
 * Model Collection
 * Application-owned grouping of library items. A collection is both an
 * organizational unit and the public sharing boundary when `shareId` is set.
 */
export type Collection = Prisma.CollectionModel
/**
 * Model LibraryActivityEvent
 * Application-owned activity record for the user's library timeline. Item and
 * collection relations are nullable so deletion preserves historical context.
 */
export type LibraryActivityEvent = Prisma.LibraryActivityEventModel
/**
 * Model LibraryItem
 * Application-owned saved content. The compound source identity is the durable
 * dedupe key; collection membership and activity hang off this record.
 */
export type LibraryItem = Prisma.LibraryItemModel
/**
 * Model Session
 * Managed by better-auth core. Do not rename fields.
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * Managed by better-auth core. Do not rename fields.
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * Managed by better-auth core. Do not rename fields.
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Subscription
 * Managed by @better-auth/stripe plugin. Do not rename fields. Cache reads this
 * table for entitlement state but should let the plugin own lifecycle writes.
 */
export type Subscription = Prisma.SubscriptionModel
/**
 * Model Feedback
 * Application-owned user feedback submissions. Feedback survives user deletion
 * so product triage keeps historical context without retaining the account.
 */
export type Feedback = Prisma.FeedbackModel
