
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * Managed by better-auth core. Do not rename fields.
 */
export type User = Prisma.UserModel
/**
 * Model Collection
 * Application-owned. Named groupings of library items.
 */
export type Collection = Prisma.CollectionModel
/**
 * Model LibraryActivityEvent
 * Application-owned. Append-only activity events for the user's library timeline.
 */
export type LibraryActivityEvent = Prisma.LibraryActivityEventModel
/**
 * Model LibraryItem
 * Application-owned. User's saved content items.
 */
export type LibraryItem = Prisma.LibraryItemModel
/**
 * Model Session
 * Managed by better-auth core. Do not rename fields.
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * Managed by better-auth core. Do not rename fields.
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * Managed by better-auth core. Do not rename fields.
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Subscription
 * Managed by @better-auth/stripe plugin. Do not rename fields.
 */
export type Subscription = Prisma.SubscriptionModel
/**
 * Model Feedback
 * Application-owned. User feedback submissions.
 */
export type Feedback = Prisma.FeedbackModel
