
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * Managed by better-auth core, with Cache-specific user preferences added.
 * Do not rename auth-owned fields; better-auth reads them by convention.
 */
export type User = Prisma.UserModel
/**
 * Model Collection
 * Application-owned grouping of library items. A collection is both an
 * organizational unit and the public sharing boundary when `shareId` is set.
 */
export type Collection = Prisma.CollectionModel
/**
 * Model LibraryActivityEvent
 * Application-owned activity record for the user's library timeline. Item and
 * collection relations are nullable so deletion preserves historical context.
 */
export type LibraryActivityEvent = Prisma.LibraryActivityEventModel
/**
 * Model LibraryItem
 * Application-owned saved content. The compound source identity is the durable
 * dedupe key; collection membership and activity hang off this record.
 */
export type LibraryItem = Prisma.LibraryItemModel
/**
 * Model Session
 * Managed by better-auth core. Do not rename fields.
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * Managed by better-auth core. Do not rename fields.
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * Managed by better-auth core. Do not rename fields.
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Subscription
 * Managed by @better-auth/stripe plugin. Do not rename fields. Cache reads this
 * table for entitlement state but should let the plugin own lifecycle writes.
 */
export type Subscription = Prisma.SubscriptionModel
/**
 * Model Feedback
 * Application-owned user feedback submissions. Feedback survives user deletion
 * so product triage keeps historical context without retaining the account.
 */
export type Feedback = Prisma.FeedbackModel
