
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const LibraryItemSource = {
  cache_note: 'cache_note',
  chrome_bookmarks: 'chrome_bookmarks',
  github_starred_repositories: 'github_starred_repositories',
  google_photos: 'google_photos',
  instagram: 'instagram',
  other: 'other',
  pinterest: 'pinterest',
  tiktok: 'tiktok',
  x_bookmarks: 'x_bookmarks',
  youtube_watch_later: 'youtube_watch_later'
} as const

export type LibraryItemSource = (typeof LibraryItemSource)[keyof typeof LibraryItemSource]


export const LibraryItemKind = {
  bookmark: 'bookmark',
  folder: 'folder',
  note: 'note'
} as const

export type LibraryItemKind = (typeof LibraryItemKind)[keyof typeof LibraryItemKind]


export const CollectionPriority = {
  none: 'none',
  very_relevant: 'very_relevant',
  relevant: 'relevant',
  peripheral: 'peripheral',
  archive: 'archive'
} as const

export type CollectionPriority = (typeof CollectionPriority)[keyof typeof CollectionPriority]


export const LibraryItemPreviewMediaType = {
  image: 'image',
  video: 'video',
  gif: 'gif',
  unknown: 'unknown'
} as const

export type LibraryItemPreviewMediaType = (typeof LibraryItemPreviewMediaType)[keyof typeof LibraryItemPreviewMediaType]


export const LibraryItemPreviewProviderStatus = {
  success: 'success',
  unavailable: 'unavailable',
  error: 'error'
} as const

export type LibraryItemPreviewProviderStatus = (typeof LibraryItemPreviewProviderStatus)[keyof typeof LibraryItemPreviewProviderStatus]


export const CollectionTemplate = {
  reading_list: 'reading_list',
  inspiration: 'inspiration',
  tutorials_guides: 'tutorials_guides',
  watch_later: 'watch_later',
  recipes: 'recipes',
  research_notes: 'research_notes',
  product_ideas: 'product_ideas',
  travel_plans: 'travel_plans',
  career_growth: 'career_growth',
  life_admin: 'life_admin'
} as const

export type CollectionTemplate = (typeof CollectionTemplate)[keyof typeof CollectionTemplate]
