
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LibraryItemPreview` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LibraryItemPreview
 * 
 */
export type LibraryItemPreviewModel = runtime.Types.Result.DefaultSelection<Prisma.$LibraryItemPreviewPayload>

export type AggregateLibraryItemPreview = {
  _count: LibraryItemPreviewCountAggregateOutputType | null
  _min: LibraryItemPreviewMinAggregateOutputType | null
  _max: LibraryItemPreviewMaxAggregateOutputType | null
}

export type LibraryItemPreviewMinAggregateOutputType = {
  id: string | null
  libraryItemId: string | null
  sourceUrl: string | null
  staticImageUrl: string | null
  videoPreviewUrl: string | null
  mediaType: $Enums.LibraryItemPreviewMediaType | null
  providerStatus: $Enums.LibraryItemPreviewProviderStatus | null
  errorCode: string | null
  resolvedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LibraryItemPreviewMaxAggregateOutputType = {
  id: string | null
  libraryItemId: string | null
  sourceUrl: string | null
  staticImageUrl: string | null
  videoPreviewUrl: string | null
  mediaType: $Enums.LibraryItemPreviewMediaType | null
  providerStatus: $Enums.LibraryItemPreviewProviderStatus | null
  errorCode: string | null
  resolvedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LibraryItemPreviewCountAggregateOutputType = {
  id: number
  libraryItemId: number
  sourceUrl: number
  staticImageUrl: number
  videoPreviewUrl: number
  mediaType: number
  providerStatus: number
  errorCode: number
  resolvedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LibraryItemPreviewMinAggregateInputType = {
  id?: true
  libraryItemId?: true
  sourceUrl?: true
  staticImageUrl?: true
  videoPreviewUrl?: true
  mediaType?: true
  providerStatus?: true
  errorCode?: true
  resolvedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type LibraryItemPreviewMaxAggregateInputType = {
  id?: true
  libraryItemId?: true
  sourceUrl?: true
  staticImageUrl?: true
  videoPreviewUrl?: true
  mediaType?: true
  providerStatus?: true
  errorCode?: true
  resolvedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type LibraryItemPreviewCountAggregateInputType = {
  id?: true
  libraryItemId?: true
  sourceUrl?: true
  staticImageUrl?: true
  videoPreviewUrl?: true
  mediaType?: true
  providerStatus?: true
  errorCode?: true
  resolvedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LibraryItemPreviewAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LibraryItemPreview to aggregate.
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryItemPreviews to fetch.
   */
  orderBy?: Prisma.LibraryItemPreviewOrderByWithRelationInput | Prisma.LibraryItemPreviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LibraryItemPreviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryItemPreviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryItemPreviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LibraryItemPreviews
  **/
  _count?: true | LibraryItemPreviewCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LibraryItemPreviewMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LibraryItemPreviewMaxAggregateInputType
}

export type GetLibraryItemPreviewAggregateType<T extends LibraryItemPreviewAggregateArgs> = {
      [P in keyof T & keyof AggregateLibraryItemPreview]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLibraryItemPreview[P]>
    : Prisma.GetScalarType<T[P], AggregateLibraryItemPreview[P]>
}




export type LibraryItemPreviewGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LibraryItemPreviewWhereInput
  orderBy?: Prisma.LibraryItemPreviewOrderByWithAggregationInput | Prisma.LibraryItemPreviewOrderByWithAggregationInput[]
  by: Prisma.LibraryItemPreviewScalarFieldEnum[] | Prisma.LibraryItemPreviewScalarFieldEnum
  having?: Prisma.LibraryItemPreviewScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LibraryItemPreviewCountAggregateInputType | true
  _min?: LibraryItemPreviewMinAggregateInputType
  _max?: LibraryItemPreviewMaxAggregateInputType
}

export type LibraryItemPreviewGroupByOutputType = {
  id: string
  libraryItemId: string
  sourceUrl: string
  staticImageUrl: string | null
  videoPreviewUrl: string | null
  mediaType: $Enums.LibraryItemPreviewMediaType
  providerStatus: $Enums.LibraryItemPreviewProviderStatus
  errorCode: string | null
  resolvedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: LibraryItemPreviewCountAggregateOutputType | null
  _min: LibraryItemPreviewMinAggregateOutputType | null
  _max: LibraryItemPreviewMaxAggregateOutputType | null
}

export type GetLibraryItemPreviewGroupByPayload<T extends LibraryItemPreviewGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LibraryItemPreviewGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LibraryItemPreviewGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LibraryItemPreviewGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LibraryItemPreviewGroupByOutputType[P]>
      }
    >
  >



export type LibraryItemPreviewWhereInput = {
  AND?: Prisma.LibraryItemPreviewWhereInput | Prisma.LibraryItemPreviewWhereInput[]
  OR?: Prisma.LibraryItemPreviewWhereInput[]
  NOT?: Prisma.LibraryItemPreviewWhereInput | Prisma.LibraryItemPreviewWhereInput[]
  id?: Prisma.StringFilter<"LibraryItemPreview"> | string
  libraryItemId?: Prisma.StringFilter<"LibraryItemPreview"> | string
  sourceUrl?: Prisma.StringFilter<"LibraryItemPreview"> | string
  staticImageUrl?: Prisma.StringNullableFilter<"LibraryItemPreview"> | string | null
  videoPreviewUrl?: Prisma.StringNullableFilter<"LibraryItemPreview"> | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFilter<"LibraryItemPreview"> | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFilter<"LibraryItemPreview"> | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.StringNullableFilter<"LibraryItemPreview"> | string | null
  resolvedAt?: Prisma.DateTimeFilter<"LibraryItemPreview"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"LibraryItemPreview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LibraryItemPreview"> | Date | string
  libraryItem?: Prisma.XOR<Prisma.LibraryItemScalarRelationFilter, Prisma.LibraryItemWhereInput>
}

export type LibraryItemPreviewOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  staticImageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  videoPreviewUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  providerStatus?: Prisma.SortOrder
  errorCode?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  libraryItem?: Prisma.LibraryItemOrderByWithRelationInput
}

export type LibraryItemPreviewWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  libraryItemId?: string
  AND?: Prisma.LibraryItemPreviewWhereInput | Prisma.LibraryItemPreviewWhereInput[]
  OR?: Prisma.LibraryItemPreviewWhereInput[]
  NOT?: Prisma.LibraryItemPreviewWhereInput | Prisma.LibraryItemPreviewWhereInput[]
  sourceUrl?: Prisma.StringFilter<"LibraryItemPreview"> | string
  staticImageUrl?: Prisma.StringNullableFilter<"LibraryItemPreview"> | string | null
  videoPreviewUrl?: Prisma.StringNullableFilter<"LibraryItemPreview"> | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFilter<"LibraryItemPreview"> | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFilter<"LibraryItemPreview"> | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.StringNullableFilter<"LibraryItemPreview"> | string | null
  resolvedAt?: Prisma.DateTimeFilter<"LibraryItemPreview"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"LibraryItemPreview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LibraryItemPreview"> | Date | string
  libraryItem?: Prisma.XOR<Prisma.LibraryItemScalarRelationFilter, Prisma.LibraryItemWhereInput>
}, "id" | "libraryItemId">

export type LibraryItemPreviewOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  staticImageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  videoPreviewUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  providerStatus?: Prisma.SortOrder
  errorCode?: Prisma.SortOrderInput | Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LibraryItemPreviewCountOrderByAggregateInput
  _max?: Prisma.LibraryItemPreviewMaxOrderByAggregateInput
  _min?: Prisma.LibraryItemPreviewMinOrderByAggregateInput
}

export type LibraryItemPreviewScalarWhereWithAggregatesInput = {
  AND?: Prisma.LibraryItemPreviewScalarWhereWithAggregatesInput | Prisma.LibraryItemPreviewScalarWhereWithAggregatesInput[]
  OR?: Prisma.LibraryItemPreviewScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LibraryItemPreviewScalarWhereWithAggregatesInput | Prisma.LibraryItemPreviewScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LibraryItemPreview"> | string
  libraryItemId?: Prisma.StringWithAggregatesFilter<"LibraryItemPreview"> | string
  sourceUrl?: Prisma.StringWithAggregatesFilter<"LibraryItemPreview"> | string
  staticImageUrl?: Prisma.StringNullableWithAggregatesFilter<"LibraryItemPreview"> | string | null
  videoPreviewUrl?: Prisma.StringNullableWithAggregatesFilter<"LibraryItemPreview"> | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeWithAggregatesFilter<"LibraryItemPreview"> | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusWithAggregatesFilter<"LibraryItemPreview"> | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.StringNullableWithAggregatesFilter<"LibraryItemPreview"> | string | null
  resolvedAt?: Prisma.DateTimeWithAggregatesFilter<"LibraryItemPreview"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LibraryItemPreview"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LibraryItemPreview"> | Date | string
}

export type LibraryItemPreviewCreateInput = {
  id?: string
  sourceUrl: string
  staticImageUrl?: string | null
  videoPreviewUrl?: string | null
  mediaType?: $Enums.LibraryItemPreviewMediaType
  providerStatus: $Enums.LibraryItemPreviewProviderStatus
  errorCode?: string | null
  resolvedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  libraryItem: Prisma.LibraryItemCreateNestedOneWithoutPreviewInput
}

export type LibraryItemPreviewUncheckedCreateInput = {
  id?: string
  libraryItemId: string
  sourceUrl: string
  staticImageUrl?: string | null
  videoPreviewUrl?: string | null
  mediaType?: $Enums.LibraryItemPreviewMediaType
  providerStatus: $Enums.LibraryItemPreviewProviderStatus
  errorCode?: string | null
  resolvedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LibraryItemPreviewUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.StringFieldUpdateOperationsInput | string
  staticImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoPreviewUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resolvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  libraryItem?: Prisma.LibraryItemUpdateOneRequiredWithoutPreviewNestedInput
}

export type LibraryItemPreviewUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  libraryItemId?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.StringFieldUpdateOperationsInput | string
  staticImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoPreviewUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resolvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryItemPreviewCreateManyInput = {
  id?: string
  libraryItemId: string
  sourceUrl: string
  staticImageUrl?: string | null
  videoPreviewUrl?: string | null
  mediaType?: $Enums.LibraryItemPreviewMediaType
  providerStatus: $Enums.LibraryItemPreviewProviderStatus
  errorCode?: string | null
  resolvedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LibraryItemPreviewUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.StringFieldUpdateOperationsInput | string
  staticImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoPreviewUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resolvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryItemPreviewUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  libraryItemId?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.StringFieldUpdateOperationsInput | string
  staticImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoPreviewUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resolvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryItemPreviewNullableScalarRelationFilter = {
  is?: Prisma.LibraryItemPreviewWhereInput | null
  isNot?: Prisma.LibraryItemPreviewWhereInput | null
}

export type LibraryItemPreviewCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  staticImageUrl?: Prisma.SortOrder
  videoPreviewUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  providerStatus?: Prisma.SortOrder
  errorCode?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LibraryItemPreviewMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  staticImageUrl?: Prisma.SortOrder
  videoPreviewUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  providerStatus?: Prisma.SortOrder
  errorCode?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LibraryItemPreviewMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  staticImageUrl?: Prisma.SortOrder
  videoPreviewUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  providerStatus?: Prisma.SortOrder
  errorCode?: Prisma.SortOrder
  resolvedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LibraryItemPreviewCreateNestedOneWithoutLibraryItemInput = {
  create?: Prisma.XOR<Prisma.LibraryItemPreviewCreateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput>
  connectOrCreate?: Prisma.LibraryItemPreviewCreateOrConnectWithoutLibraryItemInput
  connect?: Prisma.LibraryItemPreviewWhereUniqueInput
}

export type LibraryItemPreviewUncheckedCreateNestedOneWithoutLibraryItemInput = {
  create?: Prisma.XOR<Prisma.LibraryItemPreviewCreateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput>
  connectOrCreate?: Prisma.LibraryItemPreviewCreateOrConnectWithoutLibraryItemInput
  connect?: Prisma.LibraryItemPreviewWhereUniqueInput
}

export type LibraryItemPreviewUpdateOneWithoutLibraryItemNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryItemPreviewCreateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput>
  connectOrCreate?: Prisma.LibraryItemPreviewCreateOrConnectWithoutLibraryItemInput
  upsert?: Prisma.LibraryItemPreviewUpsertWithoutLibraryItemInput
  disconnect?: Prisma.LibraryItemPreviewWhereInput | boolean
  delete?: Prisma.LibraryItemPreviewWhereInput | boolean
  connect?: Prisma.LibraryItemPreviewWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LibraryItemPreviewUpdateToOneWithWhereWithoutLibraryItemInput, Prisma.LibraryItemPreviewUpdateWithoutLibraryItemInput>, Prisma.LibraryItemPreviewUncheckedUpdateWithoutLibraryItemInput>
}

export type LibraryItemPreviewUncheckedUpdateOneWithoutLibraryItemNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryItemPreviewCreateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput>
  connectOrCreate?: Prisma.LibraryItemPreviewCreateOrConnectWithoutLibraryItemInput
  upsert?: Prisma.LibraryItemPreviewUpsertWithoutLibraryItemInput
  disconnect?: Prisma.LibraryItemPreviewWhereInput | boolean
  delete?: Prisma.LibraryItemPreviewWhereInput | boolean
  connect?: Prisma.LibraryItemPreviewWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LibraryItemPreviewUpdateToOneWithWhereWithoutLibraryItemInput, Prisma.LibraryItemPreviewUpdateWithoutLibraryItemInput>, Prisma.LibraryItemPreviewUncheckedUpdateWithoutLibraryItemInput>
}

export type EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput = {
  set?: $Enums.LibraryItemPreviewMediaType
}

export type EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput = {
  set?: $Enums.LibraryItemPreviewProviderStatus
}

export type LibraryItemPreviewCreateWithoutLibraryItemInput = {
  id?: string
  sourceUrl: string
  staticImageUrl?: string | null
  videoPreviewUrl?: string | null
  mediaType?: $Enums.LibraryItemPreviewMediaType
  providerStatus: $Enums.LibraryItemPreviewProviderStatus
  errorCode?: string | null
  resolvedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput = {
  id?: string
  sourceUrl: string
  staticImageUrl?: string | null
  videoPreviewUrl?: string | null
  mediaType?: $Enums.LibraryItemPreviewMediaType
  providerStatus: $Enums.LibraryItemPreviewProviderStatus
  errorCode?: string | null
  resolvedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LibraryItemPreviewCreateOrConnectWithoutLibraryItemInput = {
  where: Prisma.LibraryItemPreviewWhereUniqueInput
  create: Prisma.XOR<Prisma.LibraryItemPreviewCreateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput>
}

export type LibraryItemPreviewUpsertWithoutLibraryItemInput = {
  update: Prisma.XOR<Prisma.LibraryItemPreviewUpdateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedUpdateWithoutLibraryItemInput>
  create: Prisma.XOR<Prisma.LibraryItemPreviewCreateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedCreateWithoutLibraryItemInput>
  where?: Prisma.LibraryItemPreviewWhereInput
}

export type LibraryItemPreviewUpdateToOneWithWhereWithoutLibraryItemInput = {
  where?: Prisma.LibraryItemPreviewWhereInput
  data: Prisma.XOR<Prisma.LibraryItemPreviewUpdateWithoutLibraryItemInput, Prisma.LibraryItemPreviewUncheckedUpdateWithoutLibraryItemInput>
}

export type LibraryItemPreviewUpdateWithoutLibraryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.StringFieldUpdateOperationsInput | string
  staticImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoPreviewUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resolvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryItemPreviewUncheckedUpdateWithoutLibraryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.StringFieldUpdateOperationsInput | string
  staticImageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoPreviewUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mediaType?: Prisma.EnumLibraryItemPreviewMediaTypeFieldUpdateOperationsInput | $Enums.LibraryItemPreviewMediaType
  providerStatus?: Prisma.EnumLibraryItemPreviewProviderStatusFieldUpdateOperationsInput | $Enums.LibraryItemPreviewProviderStatus
  errorCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resolvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LibraryItemPreviewSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  libraryItemId?: boolean
  sourceUrl?: boolean
  staticImageUrl?: boolean
  videoPreviewUrl?: boolean
  mediaType?: boolean
  providerStatus?: boolean
  errorCode?: boolean
  resolvedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  libraryItem?: boolean | Prisma.LibraryItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["libraryItemPreview"]>

export type LibraryItemPreviewSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  libraryItemId?: boolean
  sourceUrl?: boolean
  staticImageUrl?: boolean
  videoPreviewUrl?: boolean
  mediaType?: boolean
  providerStatus?: boolean
  errorCode?: boolean
  resolvedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  libraryItem?: boolean | Prisma.LibraryItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["libraryItemPreview"]>

export type LibraryItemPreviewSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  libraryItemId?: boolean
  sourceUrl?: boolean
  staticImageUrl?: boolean
  videoPreviewUrl?: boolean
  mediaType?: boolean
  providerStatus?: boolean
  errorCode?: boolean
  resolvedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  libraryItem?: boolean | Prisma.LibraryItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["libraryItemPreview"]>

export type LibraryItemPreviewSelectScalar = {
  id?: boolean
  libraryItemId?: boolean
  sourceUrl?: boolean
  staticImageUrl?: boolean
  videoPreviewUrl?: boolean
  mediaType?: boolean
  providerStatus?: boolean
  errorCode?: boolean
  resolvedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LibraryItemPreviewOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "libraryItemId" | "sourceUrl" | "staticImageUrl" | "videoPreviewUrl" | "mediaType" | "providerStatus" | "errorCode" | "resolvedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["libraryItemPreview"]>
export type LibraryItemPreviewInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  libraryItem?: boolean | Prisma.LibraryItemDefaultArgs<ExtArgs>
}
export type LibraryItemPreviewIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  libraryItem?: boolean | Prisma.LibraryItemDefaultArgs<ExtArgs>
}
export type LibraryItemPreviewIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  libraryItem?: boolean | Prisma.LibraryItemDefaultArgs<ExtArgs>
}

export type $LibraryItemPreviewPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LibraryItemPreview"
  objects: {
    libraryItem: Prisma.$LibraryItemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    libraryItemId: string
    sourceUrl: string
    staticImageUrl: string | null
    videoPreviewUrl: string | null
    mediaType: $Enums.LibraryItemPreviewMediaType
    providerStatus: $Enums.LibraryItemPreviewProviderStatus
    errorCode: string | null
    resolvedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["libraryItemPreview"]>
  composites: {}
}

export type LibraryItemPreviewGetPayload<S extends boolean | null | undefined | LibraryItemPreviewDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload, S>

export type LibraryItemPreviewCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LibraryItemPreviewFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LibraryItemPreviewCountAggregateInputType | true
  }

export interface LibraryItemPreviewDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LibraryItemPreview'], meta: { name: 'LibraryItemPreview' } }
  /**
   * Find zero or one LibraryItemPreview that matches the filter.
   * @param {LibraryItemPreviewFindUniqueArgs} args - Arguments to find a LibraryItemPreview
   * @example
   * // Get one LibraryItemPreview
   * const libraryItemPreview = await prisma.libraryItemPreview.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LibraryItemPreviewFindUniqueArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LibraryItemPreview that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LibraryItemPreviewFindUniqueOrThrowArgs} args - Arguments to find a LibraryItemPreview
   * @example
   * // Get one LibraryItemPreview
   * const libraryItemPreview = await prisma.libraryItemPreview.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LibraryItemPreviewFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LibraryItemPreview that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewFindFirstArgs} args - Arguments to find a LibraryItemPreview
   * @example
   * // Get one LibraryItemPreview
   * const libraryItemPreview = await prisma.libraryItemPreview.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LibraryItemPreviewFindFirstArgs>(args?: Prisma.SelectSubset<T, LibraryItemPreviewFindFirstArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LibraryItemPreview that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewFindFirstOrThrowArgs} args - Arguments to find a LibraryItemPreview
   * @example
   * // Get one LibraryItemPreview
   * const libraryItemPreview = await prisma.libraryItemPreview.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LibraryItemPreviewFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LibraryItemPreviewFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LibraryItemPreviews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LibraryItemPreviews
   * const libraryItemPreviews = await prisma.libraryItemPreview.findMany()
   * 
   * // Get first 10 LibraryItemPreviews
   * const libraryItemPreviews = await prisma.libraryItemPreview.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const libraryItemPreviewWithIdOnly = await prisma.libraryItemPreview.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LibraryItemPreviewFindManyArgs>(args?: Prisma.SelectSubset<T, LibraryItemPreviewFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LibraryItemPreview.
   * @param {LibraryItemPreviewCreateArgs} args - Arguments to create a LibraryItemPreview.
   * @example
   * // Create one LibraryItemPreview
   * const LibraryItemPreview = await prisma.libraryItemPreview.create({
   *   data: {
   *     // ... data to create a LibraryItemPreview
   *   }
   * })
   * 
   */
  create<T extends LibraryItemPreviewCreateArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewCreateArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LibraryItemPreviews.
   * @param {LibraryItemPreviewCreateManyArgs} args - Arguments to create many LibraryItemPreviews.
   * @example
   * // Create many LibraryItemPreviews
   * const libraryItemPreview = await prisma.libraryItemPreview.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LibraryItemPreviewCreateManyArgs>(args?: Prisma.SelectSubset<T, LibraryItemPreviewCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LibraryItemPreviews and returns the data saved in the database.
   * @param {LibraryItemPreviewCreateManyAndReturnArgs} args - Arguments to create many LibraryItemPreviews.
   * @example
   * // Create many LibraryItemPreviews
   * const libraryItemPreview = await prisma.libraryItemPreview.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LibraryItemPreviews and only return the `id`
   * const libraryItemPreviewWithIdOnly = await prisma.libraryItemPreview.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LibraryItemPreviewCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LibraryItemPreviewCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LibraryItemPreview.
   * @param {LibraryItemPreviewDeleteArgs} args - Arguments to delete one LibraryItemPreview.
   * @example
   * // Delete one LibraryItemPreview
   * const LibraryItemPreview = await prisma.libraryItemPreview.delete({
   *   where: {
   *     // ... filter to delete one LibraryItemPreview
   *   }
   * })
   * 
   */
  delete<T extends LibraryItemPreviewDeleteArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewDeleteArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LibraryItemPreview.
   * @param {LibraryItemPreviewUpdateArgs} args - Arguments to update one LibraryItemPreview.
   * @example
   * // Update one LibraryItemPreview
   * const libraryItemPreview = await prisma.libraryItemPreview.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LibraryItemPreviewUpdateArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewUpdateArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LibraryItemPreviews.
   * @param {LibraryItemPreviewDeleteManyArgs} args - Arguments to filter LibraryItemPreviews to delete.
   * @example
   * // Delete a few LibraryItemPreviews
   * const { count } = await prisma.libraryItemPreview.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LibraryItemPreviewDeleteManyArgs>(args?: Prisma.SelectSubset<T, LibraryItemPreviewDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LibraryItemPreviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LibraryItemPreviews
   * const libraryItemPreview = await prisma.libraryItemPreview.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LibraryItemPreviewUpdateManyArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LibraryItemPreviews and returns the data updated in the database.
   * @param {LibraryItemPreviewUpdateManyAndReturnArgs} args - Arguments to update many LibraryItemPreviews.
   * @example
   * // Update many LibraryItemPreviews
   * const libraryItemPreview = await prisma.libraryItemPreview.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LibraryItemPreviews and only return the `id`
   * const libraryItemPreviewWithIdOnly = await prisma.libraryItemPreview.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LibraryItemPreviewUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LibraryItemPreview.
   * @param {LibraryItemPreviewUpsertArgs} args - Arguments to update or create a LibraryItemPreview.
   * @example
   * // Update or create a LibraryItemPreview
   * const libraryItemPreview = await prisma.libraryItemPreview.upsert({
   *   create: {
   *     // ... data to create a LibraryItemPreview
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LibraryItemPreview we want to update
   *   }
   * })
   */
  upsert<T extends LibraryItemPreviewUpsertArgs>(args: Prisma.SelectSubset<T, LibraryItemPreviewUpsertArgs<ExtArgs>>): Prisma.Prisma__LibraryItemPreviewClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPreviewPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LibraryItemPreviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewCountArgs} args - Arguments to filter LibraryItemPreviews to count.
   * @example
   * // Count the number of LibraryItemPreviews
   * const count = await prisma.libraryItemPreview.count({
   *   where: {
   *     // ... the filter for the LibraryItemPreviews we want to count
   *   }
   * })
  **/
  count<T extends LibraryItemPreviewCountArgs>(
    args?: Prisma.Subset<T, LibraryItemPreviewCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LibraryItemPreviewCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LibraryItemPreview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LibraryItemPreviewAggregateArgs>(args: Prisma.Subset<T, LibraryItemPreviewAggregateArgs>): Prisma.PrismaPromise<GetLibraryItemPreviewAggregateType<T>>

  /**
   * Group by LibraryItemPreview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryItemPreviewGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LibraryItemPreviewGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LibraryItemPreviewGroupByArgs['orderBy'] }
      : { orderBy?: LibraryItemPreviewGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LibraryItemPreviewGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLibraryItemPreviewGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LibraryItemPreview model
 */
readonly fields: LibraryItemPreviewFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LibraryItemPreview.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LibraryItemPreviewClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  libraryItem<T extends Prisma.LibraryItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LibraryItemDefaultArgs<ExtArgs>>): Prisma.Prisma__LibraryItemClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LibraryItemPreview model
 */
export interface LibraryItemPreviewFieldRefs {
  readonly id: Prisma.FieldRef<"LibraryItemPreview", 'String'>
  readonly libraryItemId: Prisma.FieldRef<"LibraryItemPreview", 'String'>
  readonly sourceUrl: Prisma.FieldRef<"LibraryItemPreview", 'String'>
  readonly staticImageUrl: Prisma.FieldRef<"LibraryItemPreview", 'String'>
  readonly videoPreviewUrl: Prisma.FieldRef<"LibraryItemPreview", 'String'>
  readonly mediaType: Prisma.FieldRef<"LibraryItemPreview", 'LibraryItemPreviewMediaType'>
  readonly providerStatus: Prisma.FieldRef<"LibraryItemPreview", 'LibraryItemPreviewProviderStatus'>
  readonly errorCode: Prisma.FieldRef<"LibraryItemPreview", 'String'>
  readonly resolvedAt: Prisma.FieldRef<"LibraryItemPreview", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"LibraryItemPreview", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LibraryItemPreview", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LibraryItemPreview findUnique
 */
export type LibraryItemPreviewFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * Filter, which LibraryItemPreview to fetch.
   */
  where: Prisma.LibraryItemPreviewWhereUniqueInput
}

/**
 * LibraryItemPreview findUniqueOrThrow
 */
export type LibraryItemPreviewFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * Filter, which LibraryItemPreview to fetch.
   */
  where: Prisma.LibraryItemPreviewWhereUniqueInput
}

/**
 * LibraryItemPreview findFirst
 */
export type LibraryItemPreviewFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * Filter, which LibraryItemPreview to fetch.
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryItemPreviews to fetch.
   */
  orderBy?: Prisma.LibraryItemPreviewOrderByWithRelationInput | Prisma.LibraryItemPreviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LibraryItemPreviews.
   */
  cursor?: Prisma.LibraryItemPreviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryItemPreviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryItemPreviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LibraryItemPreviews.
   */
  distinct?: Prisma.LibraryItemPreviewScalarFieldEnum | Prisma.LibraryItemPreviewScalarFieldEnum[]
}

/**
 * LibraryItemPreview findFirstOrThrow
 */
export type LibraryItemPreviewFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * Filter, which LibraryItemPreview to fetch.
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryItemPreviews to fetch.
   */
  orderBy?: Prisma.LibraryItemPreviewOrderByWithRelationInput | Prisma.LibraryItemPreviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LibraryItemPreviews.
   */
  cursor?: Prisma.LibraryItemPreviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryItemPreviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryItemPreviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LibraryItemPreviews.
   */
  distinct?: Prisma.LibraryItemPreviewScalarFieldEnum | Prisma.LibraryItemPreviewScalarFieldEnum[]
}

/**
 * LibraryItemPreview findMany
 */
export type LibraryItemPreviewFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * Filter, which LibraryItemPreviews to fetch.
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryItemPreviews to fetch.
   */
  orderBy?: Prisma.LibraryItemPreviewOrderByWithRelationInput | Prisma.LibraryItemPreviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LibraryItemPreviews.
   */
  cursor?: Prisma.LibraryItemPreviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryItemPreviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryItemPreviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LibraryItemPreviews.
   */
  distinct?: Prisma.LibraryItemPreviewScalarFieldEnum | Prisma.LibraryItemPreviewScalarFieldEnum[]
}

/**
 * LibraryItemPreview create
 */
export type LibraryItemPreviewCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * The data needed to create a LibraryItemPreview.
   */
  data: Prisma.XOR<Prisma.LibraryItemPreviewCreateInput, Prisma.LibraryItemPreviewUncheckedCreateInput>
}

/**
 * LibraryItemPreview createMany
 */
export type LibraryItemPreviewCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LibraryItemPreviews.
   */
  data: Prisma.LibraryItemPreviewCreateManyInput | Prisma.LibraryItemPreviewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LibraryItemPreview createManyAndReturn
 */
export type LibraryItemPreviewCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * The data used to create many LibraryItemPreviews.
   */
  data: Prisma.LibraryItemPreviewCreateManyInput | Prisma.LibraryItemPreviewCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LibraryItemPreview update
 */
export type LibraryItemPreviewUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * The data needed to update a LibraryItemPreview.
   */
  data: Prisma.XOR<Prisma.LibraryItemPreviewUpdateInput, Prisma.LibraryItemPreviewUncheckedUpdateInput>
  /**
   * Choose, which LibraryItemPreview to update.
   */
  where: Prisma.LibraryItemPreviewWhereUniqueInput
}

/**
 * LibraryItemPreview updateMany
 */
export type LibraryItemPreviewUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LibraryItemPreviews.
   */
  data: Prisma.XOR<Prisma.LibraryItemPreviewUpdateManyMutationInput, Prisma.LibraryItemPreviewUncheckedUpdateManyInput>
  /**
   * Filter which LibraryItemPreviews to update
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * Limit how many LibraryItemPreviews to update.
   */
  limit?: number
}

/**
 * LibraryItemPreview updateManyAndReturn
 */
export type LibraryItemPreviewUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * The data used to update LibraryItemPreviews.
   */
  data: Prisma.XOR<Prisma.LibraryItemPreviewUpdateManyMutationInput, Prisma.LibraryItemPreviewUncheckedUpdateManyInput>
  /**
   * Filter which LibraryItemPreviews to update
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * Limit how many LibraryItemPreviews to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LibraryItemPreview upsert
 */
export type LibraryItemPreviewUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * The filter to search for the LibraryItemPreview to update in case it exists.
   */
  where: Prisma.LibraryItemPreviewWhereUniqueInput
  /**
   * In case the LibraryItemPreview found by the `where` argument doesn't exist, create a new LibraryItemPreview with this data.
   */
  create: Prisma.XOR<Prisma.LibraryItemPreviewCreateInput, Prisma.LibraryItemPreviewUncheckedCreateInput>
  /**
   * In case the LibraryItemPreview was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LibraryItemPreviewUpdateInput, Prisma.LibraryItemPreviewUncheckedUpdateInput>
}

/**
 * LibraryItemPreview delete
 */
export type LibraryItemPreviewDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
  /**
   * Filter which LibraryItemPreview to delete.
   */
  where: Prisma.LibraryItemPreviewWhereUniqueInput
}

/**
 * LibraryItemPreview deleteMany
 */
export type LibraryItemPreviewDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LibraryItemPreviews to delete
   */
  where?: Prisma.LibraryItemPreviewWhereInput
  /**
   * Limit how many LibraryItemPreviews to delete.
   */
  limit?: number
}

/**
 * LibraryItemPreview without action
 */
export type LibraryItemPreviewDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItemPreview
   */
  select?: Prisma.LibraryItemPreviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItemPreview
   */
  omit?: Prisma.LibraryItemPreviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemPreviewInclude<ExtArgs> | null
}
