
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LibraryActivityEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LibraryActivityEvent
 * Application-owned. Append-only activity events for the user's library timeline.
 */
export type LibraryActivityEventModel = runtime.Types.Result.DefaultSelection<Prisma.$LibraryActivityEventPayload>

export type AggregateLibraryActivityEvent = {
  _count: LibraryActivityEventCountAggregateOutputType | null
  _min: LibraryActivityEventMinAggregateOutputType | null
  _max: LibraryActivityEventMaxAggregateOutputType | null
}

export type LibraryActivityEventMinAggregateOutputType = {
  id: string | null
  userId: string | null
  kind: $Enums.LibraryActivityEventKind | null
  libraryItemId: string | null
  collectionId: string | null
  occurredAt: Date | null
  createdAt: Date | null
}

export type LibraryActivityEventMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  kind: $Enums.LibraryActivityEventKind | null
  libraryItemId: string | null
  collectionId: string | null
  occurredAt: Date | null
  createdAt: Date | null
}

export type LibraryActivityEventCountAggregateOutputType = {
  id: number
  userId: number
  kind: number
  libraryItemId: number
  collectionId: number
  metadata: number
  occurredAt: number
  createdAt: number
  _all: number
}


export type LibraryActivityEventMinAggregateInputType = {
  id?: true
  userId?: true
  kind?: true
  libraryItemId?: true
  collectionId?: true
  occurredAt?: true
  createdAt?: true
}

export type LibraryActivityEventMaxAggregateInputType = {
  id?: true
  userId?: true
  kind?: true
  libraryItemId?: true
  collectionId?: true
  occurredAt?: true
  createdAt?: true
}

export type LibraryActivityEventCountAggregateInputType = {
  id?: true
  userId?: true
  kind?: true
  libraryItemId?: true
  collectionId?: true
  metadata?: true
  occurredAt?: true
  createdAt?: true
  _all?: true
}

export type LibraryActivityEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LibraryActivityEvent to aggregate.
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryActivityEvents to fetch.
   */
  orderBy?: Prisma.LibraryActivityEventOrderByWithRelationInput | Prisma.LibraryActivityEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LibraryActivityEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryActivityEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryActivityEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LibraryActivityEvents
  **/
  _count?: true | LibraryActivityEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LibraryActivityEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LibraryActivityEventMaxAggregateInputType
}

export type GetLibraryActivityEventAggregateType<T extends LibraryActivityEventAggregateArgs> = {
      [P in keyof T & keyof AggregateLibraryActivityEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLibraryActivityEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateLibraryActivityEvent[P]>
}




export type LibraryActivityEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LibraryActivityEventWhereInput
  orderBy?: Prisma.LibraryActivityEventOrderByWithAggregationInput | Prisma.LibraryActivityEventOrderByWithAggregationInput[]
  by: Prisma.LibraryActivityEventScalarFieldEnum[] | Prisma.LibraryActivityEventScalarFieldEnum
  having?: Prisma.LibraryActivityEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LibraryActivityEventCountAggregateInputType | true
  _min?: LibraryActivityEventMinAggregateInputType
  _max?: LibraryActivityEventMaxAggregateInputType
}

export type LibraryActivityEventGroupByOutputType = {
  id: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId: string | null
  collectionId: string | null
  metadata: runtime.JsonValue | null
  occurredAt: Date
  createdAt: Date
  _count: LibraryActivityEventCountAggregateOutputType | null
  _min: LibraryActivityEventMinAggregateOutputType | null
  _max: LibraryActivityEventMaxAggregateOutputType | null
}

export type GetLibraryActivityEventGroupByPayload<T extends LibraryActivityEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LibraryActivityEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LibraryActivityEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LibraryActivityEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LibraryActivityEventGroupByOutputType[P]>
      }
    >
  >



export type LibraryActivityEventWhereInput = {
  AND?: Prisma.LibraryActivityEventWhereInput | Prisma.LibraryActivityEventWhereInput[]
  OR?: Prisma.LibraryActivityEventWhereInput[]
  NOT?: Prisma.LibraryActivityEventWhereInput | Prisma.LibraryActivityEventWhereInput[]
  id?: Prisma.StringFilter<"LibraryActivityEvent"> | string
  userId?: Prisma.StringFilter<"LibraryActivityEvent"> | string
  kind?: Prisma.EnumLibraryActivityEventKindFilter<"LibraryActivityEvent"> | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.StringNullableFilter<"LibraryActivityEvent"> | string | null
  collectionId?: Prisma.StringNullableFilter<"LibraryActivityEvent"> | string | null
  metadata?: Prisma.JsonNullableFilter<"LibraryActivityEvent">
  occurredAt?: Prisma.DateTimeFilter<"LibraryActivityEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"LibraryActivityEvent"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  libraryItem?: Prisma.XOR<Prisma.LibraryItemNullableScalarRelationFilter, Prisma.LibraryItemWhereInput> | null
  collection?: Prisma.XOR<Prisma.CollectionNullableScalarRelationFilter, Prisma.CollectionWhereInput> | null
}

export type LibraryActivityEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrderInput | Prisma.SortOrder
  collectionId?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  libraryItem?: Prisma.LibraryItemOrderByWithRelationInput
  collection?: Prisma.CollectionOrderByWithRelationInput
}

export type LibraryActivityEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LibraryActivityEventWhereInput | Prisma.LibraryActivityEventWhereInput[]
  OR?: Prisma.LibraryActivityEventWhereInput[]
  NOT?: Prisma.LibraryActivityEventWhereInput | Prisma.LibraryActivityEventWhereInput[]
  userId?: Prisma.StringFilter<"LibraryActivityEvent"> | string
  kind?: Prisma.EnumLibraryActivityEventKindFilter<"LibraryActivityEvent"> | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.StringNullableFilter<"LibraryActivityEvent"> | string | null
  collectionId?: Prisma.StringNullableFilter<"LibraryActivityEvent"> | string | null
  metadata?: Prisma.JsonNullableFilter<"LibraryActivityEvent">
  occurredAt?: Prisma.DateTimeFilter<"LibraryActivityEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"LibraryActivityEvent"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  libraryItem?: Prisma.XOR<Prisma.LibraryItemNullableScalarRelationFilter, Prisma.LibraryItemWhereInput> | null
  collection?: Prisma.XOR<Prisma.CollectionNullableScalarRelationFilter, Prisma.CollectionWhereInput> | null
}, "id">

export type LibraryActivityEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrderInput | Prisma.SortOrder
  collectionId?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.LibraryActivityEventCountOrderByAggregateInput
  _max?: Prisma.LibraryActivityEventMaxOrderByAggregateInput
  _min?: Prisma.LibraryActivityEventMinOrderByAggregateInput
}

export type LibraryActivityEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.LibraryActivityEventScalarWhereWithAggregatesInput | Prisma.LibraryActivityEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.LibraryActivityEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LibraryActivityEventScalarWhereWithAggregatesInput | Prisma.LibraryActivityEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LibraryActivityEvent"> | string
  userId?: Prisma.StringWithAggregatesFilter<"LibraryActivityEvent"> | string
  kind?: Prisma.EnumLibraryActivityEventKindWithAggregatesFilter<"LibraryActivityEvent"> | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.StringNullableWithAggregatesFilter<"LibraryActivityEvent"> | string | null
  collectionId?: Prisma.StringNullableWithAggregatesFilter<"LibraryActivityEvent"> | string | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"LibraryActivityEvent">
  occurredAt?: Prisma.DateTimeWithAggregatesFilter<"LibraryActivityEvent"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LibraryActivityEvent"> | Date | string
}

export type LibraryActivityEventCreateInput = {
  id?: string
  kind: $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLibraryActivityEventsInput
  libraryItem?: Prisma.LibraryItemCreateNestedOneWithoutActivityEventsInput
  collection?: Prisma.CollectionCreateNestedOneWithoutActivityEventsInput
}

export type LibraryActivityEventUncheckedCreateInput = {
  id?: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId?: string | null
  collectionId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLibraryActivityEventsNestedInput
  libraryItem?: Prisma.LibraryItemUpdateOneWithoutActivityEventsNestedInput
  collection?: Prisma.CollectionUpdateOneWithoutActivityEventsNestedInput
}

export type LibraryActivityEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventCreateManyInput = {
  id?: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId?: string | null
  collectionId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventListRelationFilter = {
  every?: Prisma.LibraryActivityEventWhereInput
  some?: Prisma.LibraryActivityEventWhereInput
  none?: Prisma.LibraryActivityEventWhereInput
}

export type LibraryActivityEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LibraryActivityEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type LibraryActivityEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type LibraryActivityEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  libraryItemId?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type LibraryActivityEventCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutUserInput, Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput> | Prisma.LibraryActivityEventCreateWithoutUserInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput | Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyUserInputEnvelope
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
}

export type LibraryActivityEventUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutUserInput, Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput> | Prisma.LibraryActivityEventCreateWithoutUserInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput | Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyUserInputEnvelope
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
}

export type LibraryActivityEventUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutUserInput, Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput> | Prisma.LibraryActivityEventCreateWithoutUserInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput | Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutUserInput | Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyUserInputEnvelope
  set?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  disconnect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  delete?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  update?: Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutUserInput | Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LibraryActivityEventUpdateManyWithWhereWithoutUserInput | Prisma.LibraryActivityEventUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
}

export type LibraryActivityEventUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutUserInput, Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput> | Prisma.LibraryActivityEventCreateWithoutUserInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput | Prisma.LibraryActivityEventCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutUserInput | Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyUserInputEnvelope
  set?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  disconnect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  delete?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  update?: Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutUserInput | Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LibraryActivityEventUpdateManyWithWhereWithoutUserInput | Prisma.LibraryActivityEventUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
}

export type LibraryActivityEventCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput> | Prisma.LibraryActivityEventCreateWithoutCollectionInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput | Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyCollectionInputEnvelope
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
}

export type LibraryActivityEventUncheckedCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput> | Prisma.LibraryActivityEventCreateWithoutCollectionInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput | Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyCollectionInputEnvelope
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
}

export type LibraryActivityEventUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput> | Prisma.LibraryActivityEventCreateWithoutCollectionInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput | Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutCollectionInput | Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyCollectionInputEnvelope
  set?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  disconnect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  delete?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  update?: Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutCollectionInput | Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.LibraryActivityEventUpdateManyWithWhereWithoutCollectionInput | Prisma.LibraryActivityEventUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
}

export type LibraryActivityEventUncheckedUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput> | Prisma.LibraryActivityEventCreateWithoutCollectionInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput | Prisma.LibraryActivityEventCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutCollectionInput | Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyCollectionInputEnvelope
  set?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  disconnect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  delete?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  update?: Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutCollectionInput | Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.LibraryActivityEventUpdateManyWithWhereWithoutCollectionInput | Prisma.LibraryActivityEventUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
}

export type EnumLibraryActivityEventKindFieldUpdateOperationsInput = {
  set?: $Enums.LibraryActivityEventKind
}

export type LibraryActivityEventCreateNestedManyWithoutLibraryItemInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput> | Prisma.LibraryActivityEventCreateWithoutLibraryItemInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput | Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyLibraryItemInputEnvelope
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
}

export type LibraryActivityEventUncheckedCreateNestedManyWithoutLibraryItemInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput> | Prisma.LibraryActivityEventCreateWithoutLibraryItemInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput | Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyLibraryItemInputEnvelope
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
}

export type LibraryActivityEventUpdateManyWithoutLibraryItemNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput> | Prisma.LibraryActivityEventCreateWithoutLibraryItemInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput | Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput[]
  upsert?: Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutLibraryItemInput | Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutLibraryItemInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyLibraryItemInputEnvelope
  set?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  disconnect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  delete?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  update?: Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutLibraryItemInput | Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutLibraryItemInput[]
  updateMany?: Prisma.LibraryActivityEventUpdateManyWithWhereWithoutLibraryItemInput | Prisma.LibraryActivityEventUpdateManyWithWhereWithoutLibraryItemInput[]
  deleteMany?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
}

export type LibraryActivityEventUncheckedUpdateManyWithoutLibraryItemNestedInput = {
  create?: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput> | Prisma.LibraryActivityEventCreateWithoutLibraryItemInput[] | Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput[]
  connectOrCreate?: Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput | Prisma.LibraryActivityEventCreateOrConnectWithoutLibraryItemInput[]
  upsert?: Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutLibraryItemInput | Prisma.LibraryActivityEventUpsertWithWhereUniqueWithoutLibraryItemInput[]
  createMany?: Prisma.LibraryActivityEventCreateManyLibraryItemInputEnvelope
  set?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  disconnect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  delete?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  connect?: Prisma.LibraryActivityEventWhereUniqueInput | Prisma.LibraryActivityEventWhereUniqueInput[]
  update?: Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutLibraryItemInput | Prisma.LibraryActivityEventUpdateWithWhereUniqueWithoutLibraryItemInput[]
  updateMany?: Prisma.LibraryActivityEventUpdateManyWithWhereWithoutLibraryItemInput | Prisma.LibraryActivityEventUpdateManyWithWhereWithoutLibraryItemInput[]
  deleteMany?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
}

export type LibraryActivityEventCreateWithoutUserInput = {
  id?: string
  kind: $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
  libraryItem?: Prisma.LibraryItemCreateNestedOneWithoutActivityEventsInput
  collection?: Prisma.CollectionCreateNestedOneWithoutActivityEventsInput
}

export type LibraryActivityEventUncheckedCreateWithoutUserInput = {
  id?: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId?: string | null
  collectionId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventCreateOrConnectWithoutUserInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutUserInput, Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput>
}

export type LibraryActivityEventCreateManyUserInputEnvelope = {
  data: Prisma.LibraryActivityEventCreateManyUserInput | Prisma.LibraryActivityEventCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type LibraryActivityEventUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  update: Prisma.XOR<Prisma.LibraryActivityEventUpdateWithoutUserInput, Prisma.LibraryActivityEventUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutUserInput, Prisma.LibraryActivityEventUncheckedCreateWithoutUserInput>
}

export type LibraryActivityEventUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateWithoutUserInput, Prisma.LibraryActivityEventUncheckedUpdateWithoutUserInput>
}

export type LibraryActivityEventUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.LibraryActivityEventScalarWhereInput
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateManyMutationInput, Prisma.LibraryActivityEventUncheckedUpdateManyWithoutUserInput>
}

export type LibraryActivityEventScalarWhereInput = {
  AND?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
  OR?: Prisma.LibraryActivityEventScalarWhereInput[]
  NOT?: Prisma.LibraryActivityEventScalarWhereInput | Prisma.LibraryActivityEventScalarWhereInput[]
  id?: Prisma.StringFilter<"LibraryActivityEvent"> | string
  userId?: Prisma.StringFilter<"LibraryActivityEvent"> | string
  kind?: Prisma.EnumLibraryActivityEventKindFilter<"LibraryActivityEvent"> | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.StringNullableFilter<"LibraryActivityEvent"> | string | null
  collectionId?: Prisma.StringNullableFilter<"LibraryActivityEvent"> | string | null
  metadata?: Prisma.JsonNullableFilter<"LibraryActivityEvent">
  occurredAt?: Prisma.DateTimeFilter<"LibraryActivityEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"LibraryActivityEvent"> | Date | string
}

export type LibraryActivityEventCreateWithoutCollectionInput = {
  id?: string
  kind: $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLibraryActivityEventsInput
  libraryItem?: Prisma.LibraryItemCreateNestedOneWithoutActivityEventsInput
}

export type LibraryActivityEventUncheckedCreateWithoutCollectionInput = {
  id?: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventCreateOrConnectWithoutCollectionInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput>
}

export type LibraryActivityEventCreateManyCollectionInputEnvelope = {
  data: Prisma.LibraryActivityEventCreateManyCollectionInput | Prisma.LibraryActivityEventCreateManyCollectionInput[]
  skipDuplicates?: boolean
}

export type LibraryActivityEventUpsertWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  update: Prisma.XOR<Prisma.LibraryActivityEventUpdateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedUpdateWithoutCollectionInput>
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedCreateWithoutCollectionInput>
}

export type LibraryActivityEventUpdateWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateWithoutCollectionInput, Prisma.LibraryActivityEventUncheckedUpdateWithoutCollectionInput>
}

export type LibraryActivityEventUpdateManyWithWhereWithoutCollectionInput = {
  where: Prisma.LibraryActivityEventScalarWhereInput
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateManyMutationInput, Prisma.LibraryActivityEventUncheckedUpdateManyWithoutCollectionInput>
}

export type LibraryActivityEventCreateWithoutLibraryItemInput = {
  id?: string
  kind: $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLibraryActivityEventsInput
  collection?: Prisma.CollectionCreateNestedOneWithoutActivityEventsInput
}

export type LibraryActivityEventUncheckedCreateWithoutLibraryItemInput = {
  id?: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  collectionId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventCreateOrConnectWithoutLibraryItemInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput>
}

export type LibraryActivityEventCreateManyLibraryItemInputEnvelope = {
  data: Prisma.LibraryActivityEventCreateManyLibraryItemInput | Prisma.LibraryActivityEventCreateManyLibraryItemInput[]
  skipDuplicates?: boolean
}

export type LibraryActivityEventUpsertWithWhereUniqueWithoutLibraryItemInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  update: Prisma.XOR<Prisma.LibraryActivityEventUpdateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedUpdateWithoutLibraryItemInput>
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedCreateWithoutLibraryItemInput>
}

export type LibraryActivityEventUpdateWithWhereUniqueWithoutLibraryItemInput = {
  where: Prisma.LibraryActivityEventWhereUniqueInput
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateWithoutLibraryItemInput, Prisma.LibraryActivityEventUncheckedUpdateWithoutLibraryItemInput>
}

export type LibraryActivityEventUpdateManyWithWhereWithoutLibraryItemInput = {
  where: Prisma.LibraryActivityEventScalarWhereInput
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateManyMutationInput, Prisma.LibraryActivityEventUncheckedUpdateManyWithoutLibraryItemInput>
}

export type LibraryActivityEventCreateManyUserInput = {
  id?: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId?: string | null
  collectionId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  libraryItem?: Prisma.LibraryItemUpdateOneWithoutActivityEventsNestedInput
  collection?: Prisma.CollectionUpdateOneWithoutActivityEventsNestedInput
}

export type LibraryActivityEventUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  collectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventCreateManyCollectionInput = {
  id?: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  libraryItemId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventUpdateWithoutCollectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLibraryActivityEventsNestedInput
  libraryItem?: Prisma.LibraryItemUpdateOneWithoutActivityEventsNestedInput
}

export type LibraryActivityEventUncheckedUpdateWithoutCollectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventUncheckedUpdateManyWithoutCollectionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  libraryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventCreateManyLibraryItemInput = {
  id?: string
  userId: string
  kind: $Enums.LibraryActivityEventKind
  collectionId?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Date | string
  createdAt?: Date | string
}

export type LibraryActivityEventUpdateWithoutLibraryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLibraryActivityEventsNestedInput
  collection?: Prisma.CollectionUpdateOneWithoutActivityEventsNestedInput
}

export type LibraryActivityEventUncheckedUpdateWithoutLibraryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  collectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LibraryActivityEventUncheckedUpdateManyWithoutLibraryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumLibraryActivityEventKindFieldUpdateOperationsInput | $Enums.LibraryActivityEventKind
  collectionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LibraryActivityEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kind?: boolean
  libraryItemId?: boolean
  collectionId?: boolean
  metadata?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  libraryItem?: boolean | Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>
  collection?: boolean | Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>
}, ExtArgs["result"]["libraryActivityEvent"]>

export type LibraryActivityEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kind?: boolean
  libraryItemId?: boolean
  collectionId?: boolean
  metadata?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  libraryItem?: boolean | Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>
  collection?: boolean | Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>
}, ExtArgs["result"]["libraryActivityEvent"]>

export type LibraryActivityEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  kind?: boolean
  libraryItemId?: boolean
  collectionId?: boolean
  metadata?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  libraryItem?: boolean | Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>
  collection?: boolean | Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>
}, ExtArgs["result"]["libraryActivityEvent"]>

export type LibraryActivityEventSelectScalar = {
  id?: boolean
  userId?: boolean
  kind?: boolean
  libraryItemId?: boolean
  collectionId?: boolean
  metadata?: boolean
  occurredAt?: boolean
  createdAt?: boolean
}

export type LibraryActivityEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "kind" | "libraryItemId" | "collectionId" | "metadata" | "occurredAt" | "createdAt", ExtArgs["result"]["libraryActivityEvent"]>
export type LibraryActivityEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  libraryItem?: boolean | Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>
  collection?: boolean | Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>
}
export type LibraryActivityEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  libraryItem?: boolean | Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>
  collection?: boolean | Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>
}
export type LibraryActivityEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  libraryItem?: boolean | Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>
  collection?: boolean | Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>
}

export type $LibraryActivityEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LibraryActivityEvent"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    libraryItem: Prisma.$LibraryItemPayload<ExtArgs> | null
    collection: Prisma.$CollectionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    kind: $Enums.LibraryActivityEventKind
    libraryItemId: string | null
    collectionId: string | null
    metadata: runtime.JsonValue | null
    occurredAt: Date
    createdAt: Date
  }, ExtArgs["result"]["libraryActivityEvent"]>
  composites: {}
}

export type LibraryActivityEventGetPayload<S extends boolean | null | undefined | LibraryActivityEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload, S>

export type LibraryActivityEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LibraryActivityEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LibraryActivityEventCountAggregateInputType | true
  }

export interface LibraryActivityEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LibraryActivityEvent'], meta: { name: 'LibraryActivityEvent' } }
  /**
   * Find zero or one LibraryActivityEvent that matches the filter.
   * @param {LibraryActivityEventFindUniqueArgs} args - Arguments to find a LibraryActivityEvent
   * @example
   * // Get one LibraryActivityEvent
   * const libraryActivityEvent = await prisma.libraryActivityEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LibraryActivityEventFindUniqueArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LibraryActivityEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LibraryActivityEventFindUniqueOrThrowArgs} args - Arguments to find a LibraryActivityEvent
   * @example
   * // Get one LibraryActivityEvent
   * const libraryActivityEvent = await prisma.libraryActivityEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LibraryActivityEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LibraryActivityEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventFindFirstArgs} args - Arguments to find a LibraryActivityEvent
   * @example
   * // Get one LibraryActivityEvent
   * const libraryActivityEvent = await prisma.libraryActivityEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LibraryActivityEventFindFirstArgs>(args?: Prisma.SelectSubset<T, LibraryActivityEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LibraryActivityEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventFindFirstOrThrowArgs} args - Arguments to find a LibraryActivityEvent
   * @example
   * // Get one LibraryActivityEvent
   * const libraryActivityEvent = await prisma.libraryActivityEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LibraryActivityEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LibraryActivityEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LibraryActivityEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LibraryActivityEvents
   * const libraryActivityEvents = await prisma.libraryActivityEvent.findMany()
   * 
   * // Get first 10 LibraryActivityEvents
   * const libraryActivityEvents = await prisma.libraryActivityEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const libraryActivityEventWithIdOnly = await prisma.libraryActivityEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LibraryActivityEventFindManyArgs>(args?: Prisma.SelectSubset<T, LibraryActivityEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LibraryActivityEvent.
   * @param {LibraryActivityEventCreateArgs} args - Arguments to create a LibraryActivityEvent.
   * @example
   * // Create one LibraryActivityEvent
   * const LibraryActivityEvent = await prisma.libraryActivityEvent.create({
   *   data: {
   *     // ... data to create a LibraryActivityEvent
   *   }
   * })
   * 
   */
  create<T extends LibraryActivityEventCreateArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventCreateArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LibraryActivityEvents.
   * @param {LibraryActivityEventCreateManyArgs} args - Arguments to create many LibraryActivityEvents.
   * @example
   * // Create many LibraryActivityEvents
   * const libraryActivityEvent = await prisma.libraryActivityEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LibraryActivityEventCreateManyArgs>(args?: Prisma.SelectSubset<T, LibraryActivityEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LibraryActivityEvents and returns the data saved in the database.
   * @param {LibraryActivityEventCreateManyAndReturnArgs} args - Arguments to create many LibraryActivityEvents.
   * @example
   * // Create many LibraryActivityEvents
   * const libraryActivityEvent = await prisma.libraryActivityEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LibraryActivityEvents and only return the `id`
   * const libraryActivityEventWithIdOnly = await prisma.libraryActivityEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LibraryActivityEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LibraryActivityEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LibraryActivityEvent.
   * @param {LibraryActivityEventDeleteArgs} args - Arguments to delete one LibraryActivityEvent.
   * @example
   * // Delete one LibraryActivityEvent
   * const LibraryActivityEvent = await prisma.libraryActivityEvent.delete({
   *   where: {
   *     // ... filter to delete one LibraryActivityEvent
   *   }
   * })
   * 
   */
  delete<T extends LibraryActivityEventDeleteArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventDeleteArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LibraryActivityEvent.
   * @param {LibraryActivityEventUpdateArgs} args - Arguments to update one LibraryActivityEvent.
   * @example
   * // Update one LibraryActivityEvent
   * const libraryActivityEvent = await prisma.libraryActivityEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LibraryActivityEventUpdateArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventUpdateArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LibraryActivityEvents.
   * @param {LibraryActivityEventDeleteManyArgs} args - Arguments to filter LibraryActivityEvents to delete.
   * @example
   * // Delete a few LibraryActivityEvents
   * const { count } = await prisma.libraryActivityEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LibraryActivityEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, LibraryActivityEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LibraryActivityEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LibraryActivityEvents
   * const libraryActivityEvent = await prisma.libraryActivityEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LibraryActivityEventUpdateManyArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LibraryActivityEvents and returns the data updated in the database.
   * @param {LibraryActivityEventUpdateManyAndReturnArgs} args - Arguments to update many LibraryActivityEvents.
   * @example
   * // Update many LibraryActivityEvents
   * const libraryActivityEvent = await prisma.libraryActivityEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LibraryActivityEvents and only return the `id`
   * const libraryActivityEventWithIdOnly = await prisma.libraryActivityEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LibraryActivityEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LibraryActivityEvent.
   * @param {LibraryActivityEventUpsertArgs} args - Arguments to update or create a LibraryActivityEvent.
   * @example
   * // Update or create a LibraryActivityEvent
   * const libraryActivityEvent = await prisma.libraryActivityEvent.upsert({
   *   create: {
   *     // ... data to create a LibraryActivityEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LibraryActivityEvent we want to update
   *   }
   * })
   */
  upsert<T extends LibraryActivityEventUpsertArgs>(args: Prisma.SelectSubset<T, LibraryActivityEventUpsertArgs<ExtArgs>>): Prisma.Prisma__LibraryActivityEventClient<runtime.Types.Result.GetResult<Prisma.$LibraryActivityEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LibraryActivityEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventCountArgs} args - Arguments to filter LibraryActivityEvents to count.
   * @example
   * // Count the number of LibraryActivityEvents
   * const count = await prisma.libraryActivityEvent.count({
   *   where: {
   *     // ... the filter for the LibraryActivityEvents we want to count
   *   }
   * })
  **/
  count<T extends LibraryActivityEventCountArgs>(
    args?: Prisma.Subset<T, LibraryActivityEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LibraryActivityEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LibraryActivityEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LibraryActivityEventAggregateArgs>(args: Prisma.Subset<T, LibraryActivityEventAggregateArgs>): Prisma.PrismaPromise<GetLibraryActivityEventAggregateType<T>>

  /**
   * Group by LibraryActivityEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LibraryActivityEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LibraryActivityEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LibraryActivityEventGroupByArgs['orderBy'] }
      : { orderBy?: LibraryActivityEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LibraryActivityEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLibraryActivityEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LibraryActivityEvent model
 */
readonly fields: LibraryActivityEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LibraryActivityEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LibraryActivityEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  libraryItem<T extends Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LibraryActivityEvent$libraryItemArgs<ExtArgs>>): Prisma.Prisma__LibraryItemClient<runtime.Types.Result.GetResult<Prisma.$LibraryItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  collection<T extends Prisma.LibraryActivityEvent$collectionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LibraryActivityEvent$collectionArgs<ExtArgs>>): Prisma.Prisma__CollectionClient<runtime.Types.Result.GetResult<Prisma.$CollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LibraryActivityEvent model
 */
export interface LibraryActivityEventFieldRefs {
  readonly id: Prisma.FieldRef<"LibraryActivityEvent", 'String'>
  readonly userId: Prisma.FieldRef<"LibraryActivityEvent", 'String'>
  readonly kind: Prisma.FieldRef<"LibraryActivityEvent", 'LibraryActivityEventKind'>
  readonly libraryItemId: Prisma.FieldRef<"LibraryActivityEvent", 'String'>
  readonly collectionId: Prisma.FieldRef<"LibraryActivityEvent", 'String'>
  readonly metadata: Prisma.FieldRef<"LibraryActivityEvent", 'Json'>
  readonly occurredAt: Prisma.FieldRef<"LibraryActivityEvent", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"LibraryActivityEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LibraryActivityEvent findUnique
 */
export type LibraryActivityEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * Filter, which LibraryActivityEvent to fetch.
   */
  where: Prisma.LibraryActivityEventWhereUniqueInput
}

/**
 * LibraryActivityEvent findUniqueOrThrow
 */
export type LibraryActivityEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * Filter, which LibraryActivityEvent to fetch.
   */
  where: Prisma.LibraryActivityEventWhereUniqueInput
}

/**
 * LibraryActivityEvent findFirst
 */
export type LibraryActivityEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * Filter, which LibraryActivityEvent to fetch.
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryActivityEvents to fetch.
   */
  orderBy?: Prisma.LibraryActivityEventOrderByWithRelationInput | Prisma.LibraryActivityEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LibraryActivityEvents.
   */
  cursor?: Prisma.LibraryActivityEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryActivityEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryActivityEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LibraryActivityEvents.
   */
  distinct?: Prisma.LibraryActivityEventScalarFieldEnum | Prisma.LibraryActivityEventScalarFieldEnum[]
}

/**
 * LibraryActivityEvent findFirstOrThrow
 */
export type LibraryActivityEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * Filter, which LibraryActivityEvent to fetch.
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryActivityEvents to fetch.
   */
  orderBy?: Prisma.LibraryActivityEventOrderByWithRelationInput | Prisma.LibraryActivityEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LibraryActivityEvents.
   */
  cursor?: Prisma.LibraryActivityEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryActivityEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryActivityEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LibraryActivityEvents.
   */
  distinct?: Prisma.LibraryActivityEventScalarFieldEnum | Prisma.LibraryActivityEventScalarFieldEnum[]
}

/**
 * LibraryActivityEvent findMany
 */
export type LibraryActivityEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * Filter, which LibraryActivityEvents to fetch.
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LibraryActivityEvents to fetch.
   */
  orderBy?: Prisma.LibraryActivityEventOrderByWithRelationInput | Prisma.LibraryActivityEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LibraryActivityEvents.
   */
  cursor?: Prisma.LibraryActivityEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LibraryActivityEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LibraryActivityEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LibraryActivityEvents.
   */
  distinct?: Prisma.LibraryActivityEventScalarFieldEnum | Prisma.LibraryActivityEventScalarFieldEnum[]
}

/**
 * LibraryActivityEvent create
 */
export type LibraryActivityEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * The data needed to create a LibraryActivityEvent.
   */
  data: Prisma.XOR<Prisma.LibraryActivityEventCreateInput, Prisma.LibraryActivityEventUncheckedCreateInput>
}

/**
 * LibraryActivityEvent createMany
 */
export type LibraryActivityEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LibraryActivityEvents.
   */
  data: Prisma.LibraryActivityEventCreateManyInput | Prisma.LibraryActivityEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LibraryActivityEvent createManyAndReturn
 */
export type LibraryActivityEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * The data used to create many LibraryActivityEvents.
   */
  data: Prisma.LibraryActivityEventCreateManyInput | Prisma.LibraryActivityEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LibraryActivityEvent update
 */
export type LibraryActivityEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * The data needed to update a LibraryActivityEvent.
   */
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateInput, Prisma.LibraryActivityEventUncheckedUpdateInput>
  /**
   * Choose, which LibraryActivityEvent to update.
   */
  where: Prisma.LibraryActivityEventWhereUniqueInput
}

/**
 * LibraryActivityEvent updateMany
 */
export type LibraryActivityEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LibraryActivityEvents.
   */
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateManyMutationInput, Prisma.LibraryActivityEventUncheckedUpdateManyInput>
  /**
   * Filter which LibraryActivityEvents to update
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * Limit how many LibraryActivityEvents to update.
   */
  limit?: number
}

/**
 * LibraryActivityEvent updateManyAndReturn
 */
export type LibraryActivityEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * The data used to update LibraryActivityEvents.
   */
  data: Prisma.XOR<Prisma.LibraryActivityEventUpdateManyMutationInput, Prisma.LibraryActivityEventUncheckedUpdateManyInput>
  /**
   * Filter which LibraryActivityEvents to update
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * Limit how many LibraryActivityEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LibraryActivityEvent upsert
 */
export type LibraryActivityEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * The filter to search for the LibraryActivityEvent to update in case it exists.
   */
  where: Prisma.LibraryActivityEventWhereUniqueInput
  /**
   * In case the LibraryActivityEvent found by the `where` argument doesn't exist, create a new LibraryActivityEvent with this data.
   */
  create: Prisma.XOR<Prisma.LibraryActivityEventCreateInput, Prisma.LibraryActivityEventUncheckedCreateInput>
  /**
   * In case the LibraryActivityEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LibraryActivityEventUpdateInput, Prisma.LibraryActivityEventUncheckedUpdateInput>
}

/**
 * LibraryActivityEvent delete
 */
export type LibraryActivityEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
  /**
   * Filter which LibraryActivityEvent to delete.
   */
  where: Prisma.LibraryActivityEventWhereUniqueInput
}

/**
 * LibraryActivityEvent deleteMany
 */
export type LibraryActivityEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LibraryActivityEvents to delete
   */
  where?: Prisma.LibraryActivityEventWhereInput
  /**
   * Limit how many LibraryActivityEvents to delete.
   */
  limit?: number
}

/**
 * LibraryActivityEvent.libraryItem
 */
export type LibraryActivityEvent$libraryItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryItem
   */
  select?: Prisma.LibraryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryItem
   */
  omit?: Prisma.LibraryItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryItemInclude<ExtArgs> | null
  where?: Prisma.LibraryItemWhereInput
}

/**
 * LibraryActivityEvent.collection
 */
export type LibraryActivityEvent$collectionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Collection
   */
  select?: Prisma.CollectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Collection
   */
  omit?: Prisma.CollectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CollectionInclude<ExtArgs> | null
  where?: Prisma.CollectionWhereInput
}

/**
 * LibraryActivityEvent without action
 */
export type LibraryActivityEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LibraryActivityEvent
   */
  select?: Prisma.LibraryActivityEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LibraryActivityEvent
   */
  omit?: Prisma.LibraryActivityEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LibraryActivityEventInclude<ExtArgs> | null
}
