export const COBALT_SUPPORTED_HOSTS = new Set([
    "bilibili.com",
    "www.bilibili.com",
    "bsky.app",
    "www.bsky.app",
    "dailymotion.com",
    "www.dailymotion.com",
    "instagram.com",
    "www.instagram.com",
    "facebook.com",
    "www.facebook.com",
    "m.facebook.com",
    "fb.watch",
    "loom.com",
    "www.loom.com",
    "newgrounds.com",
    "www.newgrounds.com",
    "ok.ru",
    "www.ok.ru",
    "pinterest.com",
    "www.pinterest.com",
    "pin.it",
    "reddit.com",
    "www.reddit.com",
    "rutube.ru",
    "www.rutube.ru",
    "snapchat.com",
    "www.snapchat.com",
    "soundcloud.com",
    "www.soundcloud.com",
    "streamable.com",
    "www.streamable.com",
    "tiktok.com",
    "www.tiktok.com",
    "m.tiktok.com",
    "vm.tiktok.com",
    "vt.tiktok.com",
    "tumblr.com",
    "www.tumblr.com",
    "twitch.tv",
    "www.twitch.tv",
    "clips.twitch.tv",
    "twitter.com",
    "www.twitter.com",
    "mobile.twitter.com",
    "x.com",
    "www.x.com",
    "mobile.x.com",
    "vimeo.com",
    "www.vimeo.com",
    "vk.com",
    "www.vk.com",
    "youtube.com",
    "www.youtube.com",
    "m.youtube.com",
    "youtu.be",
    "music.youtube.com",
]);

export function isCobaltHost(url: string): boolean {
    try {
        return COBALT_SUPPORTED_HOSTS.has(new URL(url).hostname);
    } catch {
        return false;
    }
}
